/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
    export interface GlobalComponents {
        ElAside: typeof import('element-plus/es')['ElAside'];
        ElBreadcrumb: typeof import('element-plus/es')['ElBreadcrumb'];
        ElBreadcrumbItem: typeof import('element-plus/es')['ElBreadcrumbItem'];
        ElButton: typeof import('element-plus/es')['ElButton'];
        ElCard: typeof import('element-plus/es')['ElCard'];
        ElCheckbox: typeof import('element-plus/es')['ElCheckbox'];
        ElContainer: typeof import('element-plus/es')['ElContainer'];
        ElDropdown: typeof import('element-plus/es')['ElDropdown'];
        ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem'];
        ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu'];
        ElHeader: typeof import('element-plus/es')['ElHeader'];
        ElIcon: typeof import('element-plus/es')['ElIcon'];
        ElInput: typeof import('element-plus/es')['ElInput'];
        ElMain: typeof import('element-plus/es')['ElMain'];
        ElMenu: typeof import('element-plus/es')['ElMenu'];
        ElMenuItem: typeof import('element-plus/es')['ElMenuItem'];
        ElPagination: typeof import('element-plus/es')['ElPagination'];
        ElSubMenu: typeof import('element-plus/es')['ElSubMenu'];
        ElTable: typeof import('element-plus/es')['ElTable'];
        ElTableColumn: typeof import('element-plus/es')['ElTableColumn'];
        IEpAvatar: typeof import('~icons/ep/avatar')['default'];
        IEpHouse: typeof import('~icons/ep/house')['default'];
        IEpSearch: typeof import('~icons/ep/search')['default'];
        IEpStopwatch: typeof import('~icons/ep/stopwatch')['default'];
        IEpTickets: typeof import('~icons/ep/tickets')['default'];
        LeftNav: typeof import('./src/components/left-nav.vue')['default'];
        RouterLink: typeof import('vue-router')['RouterLink'];
        RouterView: typeof import('vue-router')['RouterView'];
        TopNav: typeof import('./src/components/top-nav.vue')['default'];
    }
}
